/**
 * utils/xml.ts
 * ------------
 * - Author: V. Puska
 * - Date: 23 Nov 2024
 *
 * Helper library for phi-load module.  Takes an object generated by the ```xml-js```
 * library and re-casts it to our custom ```XmlElement``` class to make the data easier
 * to work with.
 **/


import xmljs = require("xml-js");


type Xml2JsObject = {
    type: string;
    name: string;
    text?: string;
    attributes?: Object;
    elements?: Array<Xml2JsObject>;
}

export class XmlElement {

    readonly obj: Xml2JsObject;
    readonly type: string;
    readonly tag: string;
    readonly text: string = "";
    readonly attributes: Object = {};
    readonly content: Array<Xml2JsObject> = [];

    static fromXML(xml:any): XmlElement {
        //return new XmlElement(xmljs.xml2js(xml).elements[0]);
        return new XmlElement(xmljs.xml2js(xml).elements[0]);
    }

    constructor(xml2jsObject: Xml2JsObject) {
        this.obj = xml2jsObject;
        this.type = xml2jsObject.type;
        this.tag = xml2jsObject.name;
        if (xml2jsObject.hasOwnProperty("attributes"))
            this.attributes = xml2jsObject.attributes;
        if (xml2jsObject.hasOwnProperty("elements"))
            this.content = xml2jsObject.elements;
        if (this.content.length === 1 && this.content[0].type === "text") {
            this.text = this.content[0].text;
            this.content = [];
        }

    }

    findAll(tag: string) : XmlElement[] {
        let result: XmlElement[] = [];
        for (const item of this.content) {
            let element = new XmlElement(item);
            if (element.tag === tag)
                result.push(element)
        }
        return result;
    }

    find(tag: string) {
        let result = this.findAll(tag);
        if (result.length > 0)
            return result[0]
        else
            return new XmlElement({
                type: "element",
                name: tag,
            });
    }
}
