###

POST http://localhost:3000/products/search
Content-Type: application/json
Accept-Encoding: gzip, deflate

{
  "numberOfAdults": 2,
  "hospitalCover": true,
  "generalCover": true,
  "youngAdultCover": true,
  "state": "WA"
}
